name: cosmos_sdk
description: Engage seamlessly with a Cosmos SDK-based network (cosmos hub, osmosis, thor, kujira and etc ... ), enabling the creation, signing, and transmission of transactions. (Beta version)
version: 3.1.0
homepage: "https://github.com/mrtnetwork/cosmos_sdk"
repository: "https://github.com/mrtnetwork/cosmos_sdk"
Author: mrhaydari.t@gmail.com
topics:
  - cosmos
  - wallet
  - osmosis
  - thor
  - maya
  
environment:
  sdk: '>=3.7.0 <4.0.0'
# Add regular dependencies here.
dependencies:
  blockchain_utils: ^6.0.0
  # blockchain_utils:
  #   path: ../blockchain_utils

    

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  flutter_lints: ^6.0.0
  http: ^1.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/chains.json
  
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
